[project]
name = "docling2obsidian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ahsuunn", email = "themalique1910@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "docling>=2.129.0",
]

[project.scripts]
docling2obsidian = "docling2obsidian:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
